# Generated by Django 3.2 on 2022-05-18 08:49

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max-100', max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='format: required, letters, numbers, hyphens, underscores', max_length=150, unique=True, verbose_name='Category safe URL')),
                ('is_active', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='format: not required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.category', verbose_name='Parent of Category')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max-100', max_length=255, unique=True, verbose_name='Product Name')),
                ('web_id', models.CharField(help_text='format: required, max-50, unique', max_length=50, unique=True, verbose_name='Product Web ID')),
                ('slug', models.SlugField(help_text='format: required, letters, numbers, hyphens, underscores', max_length=150, unique=True, verbose_name='Product safe URL')),
                ('description', models.TextField(help_text='format: required, max-1000', max_length=1000, verbose_name='Product Description')),
                ('is_active', models.BooleanField(default=False, help_text='format: required, boolean, true=product is visible, false=product is hidden', verbose_name='Product visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: required', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: required', verbose_name='Updated at')),
                ('category', mptt.fields.TreeManyToManyField(to='inventory.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
